# Host: desktop (from previous nwg-displays export on dusk). Edit via nwg-displays on this machine.

monitor=HDMI-A-1,1920x1080@74.97,1920x0,1.0
monitor=HDMI-A-1,transform,1
monitor=DP-2,1920x1080@165.0,0x377,1.0

workspace=1,monitor:DP-2,default:true
